AspNetMVC/Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AspNetMVC.Models
{
    public class StudentModel
    {
        private static List<Student> students = new List<Student>
            {
                new Student{StudentId=1, FullName="Ali Omar", Email="ali_omar@yahoo.com", IsEnrol=true},
                 new Student{StudentId=2, FullName="Sarah Othman", Email="sarah.othman@gmail.com", IsEnrol=true},
                  new Student{StudentId=3, FullName="Saad Suliman", Email="saad.suliman2020@gmail.com", IsEnrol=true}
            };
        public static List<Student> GetStudent()
        {

            return students;
        }
    }
    public class Student
    {
        [Display(Name = "Student Id:")]
        public int StudentId { get; set; }

        [Display(Name = "Full Name:")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Full name is required")]
        public string FullName { get; set; }      


        [Display(Name = "Email Address:")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Email address is required")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }


        [Display(Name = "Confirm Email")]
        [Compare("Email", ErrorMessage = "The Email and Confirm Email fields do not match.")]
        public string ConfirmEmail { get; set; }

        [Display(Name = "Is enrolled:")]
        public bool IsEnrol { get; set; }
    }
}

AspNetMVC/Controllers/CrudListController.cs
using AspNetMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace AspNetMVC.Controllers
{
    public class CrudListController : Controller
    {
        
        private List<Student> students = StudentModel.GetStudent();

        // GET: CrudList
        public ActionResult Index()
        {
            return View(students);
        }
        public ActionResult StudentDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student st = students.Find(s => s.StudentId == id);
            if (st == null)
            {
                return HttpNotFound();
            }
            return View(st);
        }



        // GET: Student/ UpdateStudentDetails/5
        public ActionResult UpdateStudent(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = students.Find(s => s.StudentId == id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Students/ UpdateStudentDetails/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateStudent([Bind(Include = "StudentId,FullName,Email,ConfirmEmail,IsEnrol")] Student student)
        {
            if (ModelState.IsValid)
            {
                var st = students.FirstOrDefault(s => s.StudentId == student.StudentId);
                if (st != null) { st.FullName = student.FullName; st.Email = student.Email; st.IsEnrol = student.IsEnrol; }
                return RedirectToAction("Index");

            }
            return View(student);
        }
        //============= Create New Student =================
        public ActionResult AddStudent()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddStudent([Bind(Include = "StudentId,FullName,Email, ConfirmEmail,IsEnrol")] Student student)
        {
            if (ModelState.IsValid)
            {
                if (students.Count < 50) students.Add(student);
                return RedirectToAction("Index");
            }

            return View(student);
        }

        // GET: Student/DeleteStudent/ 
        public ActionResult DeleteStudent(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = students.Find(s => s.StudentId == id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Student/DeleteStudent/5
        [HttpPost, ActionName("DeleteStudent")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteStudentConfirmed(int id)
        {
            Student student = students.Find(s => s.StudentId == id);
            if (student != null)
                students.Remove(student);

             //or we can use the next  if there is more than one match: 
             //  students.RemoveAll(s => s.StudenId == id) 

            return RedirectToAction("Index");
        }       

    }
}

AspNetMVC/Controllers/TutorialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AspNetMVC.Controllers
{
    public class TutorialController : Controller
    {
        // GET: Tutorial
        public ActionResult Index()
        {
            return View();
        }
    }
}

AspNetMVC/Views/CrudList/AddStudent.cshtml
@model AspNetMVC.Models.Student

@{
    ViewBag.Title = "AddStudent";
}

<h2>Add Student</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Add New Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.StudentId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentId, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsEnrol, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsEnrol)
                    @Html.ValidationMessageFor(model => model.IsEnrol, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-purple" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AspNetMVC/Views/CrudList/DeleteStudent.cshtml
@model AspNetMVC.Models.Student

@{
    ViewBag.Title = "DeleteStudent";
}

<h2>Delete Student</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StudentId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StudentId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
                
        <dt>
            @Html.DisplayNameFor(model => model.IsEnrol)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsEnrol)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-purple" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AspNetMVC/Views/CrudList/Index.cshtml
@model IEnumerable<AspNetMVC.Models.Student>

@{
    ViewBag.Title = "CRUD List";
}

<h2>Student List</h2>

<p>
    @Html.ActionLink("New Student", "AddStudent",
      null, new Dictionary<string, object>
      { { "data-toggle", "tooltip" },
          { "data-placement", "right" },
          { "title", "Click here to add new student" } })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.StudentId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
      
        <th>
            @Html.DisplayNameFor(model => model.IsEnrol)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.StudentId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsEnrol)
        </td>
        <td>
            @Html.ActionLink("Edit", "UpdateStudent", new { id=item.StudentId }) |
            @Html.ActionLink("Details", "StudentDetails", new { id=item.StudentId }) |
            @Html.ActionLink("Delete", "DeleteStudent", new { id=item.StudentId })
        </td>
    </tr>
}

</table>

<div>
    @Html.ActionLink("Back to the tutorial home page", "Index", "Tutorial")
</div>

AspNetMVC/Views/CrudList/StudentDetails.cshtml
@model AspNetMVC.Models.Student

@{
    ViewBag.Title = "StudentDetails";
}

<h2>Student Details</h2>

<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StudentId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StudentId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.IsEnrol)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsEnrol)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "UpdateStudent", new { id = Model.StudentId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AspNetMVC/Views/CrudList/UpdateStudent.cshtml
@model AspNetMVC.Models.Student

@{
    ViewBag.Title = "UpdateStudent";
}

<h2>Update Student</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StudentId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentId, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmEmail, "", new { @class = "text-danger" })
            </div>
        </div>      

        <div class="form-group">
            @Html.LabelFor(model => model.IsEnrol, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsEnrol)
                    @Html.ValidationMessageFor(model => model.IsEnrol, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-purple" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AspNetMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ASP.NET MVC5 Tutorial</title>
    
    <link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               <!-- @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })-->
                <a class="navbar-brand" href="https://alfaone.azurewebsites.net/"><strong>AlfaOne</strong>  </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - by <a href="https://alfaone.azurewebsites.net/" rel="nofollow">  Adel Hassan</a></p>
        </footer>
    </div>
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
</body>
</html>

AspNetMVC/Views/Tutorial/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>ASP.NET MVC5 Tutorial</h2>
<p>
    <h4> List of tutorials  </h4>
</p>
 

<table class="table">
    <tr>
        <th>
            <h3>Project Name</h3>
        </th>
        <th>
            <h3>Project Demo</h3>
        </th>
        <th>
            <h3>Project Code</h3>
        </th>
        <th>
            <h3>Details</h3> 
        </th>
    </tr>
    <tr>
        <td>
            <h5>CRUD with List</h5>
        </td>
        <td>
            @Html.ActionLink("Project Demo", "Index", "CrudList")
        </td>
        <td>
             <a href="https://github.com/Adel-alfa/MVCTutorial" rel="nofollow"> GitHub  </a> 
        </td>
        <td>
             @Html.ActionLink("Read Me", null, null, new Dictionary<string, object>
              { { "data-toggle", "tooltip" }, { "data-placement", "right" },
              { "title","Coming soon!"} }) 
             
        </td>
    </tr>

    <tr>
        <td>
            <h5>Login and Registration form</h5>
        </td>
        <td>
            @Html.ActionLink("Demo", null, null, new Dictionary<string, object>
              { { "data-toggle", "tooltip" }, { "data-placement", "right" },
              { "title","Coming soon!"} }) 
        </td>
        <td>
             @*@Html.ActionLink("GitHub", null, null, new Dictionary<string, object>
                { { "data-toggle", "tooltip" }, { "data-placement", "right" },
                { "title","Coming soon!"} })*@ 
        </td>
        <td>
           @*@Html.ActionLink("Read Me", null, null, new Dictionary<string, object>
             { { "data-toggle", "tooltip" }, { "data-placement", "right" },
             { "title","Coming soon!"} })*@ 
        </td>

    </tr>

</table>